name: "Deemix with telegram bot"
slug: "deemix"
version: "4.7.0-3"
description: "High-quality music downloader with a telegram bot: remote, chat-based control for automated downloads."
url: "https://github.com/theodorx7/ha-deemix/"
image: "ghcr.io/theodorx7/ha-deemix"
backup_exclude:
  - "**/logs/**"
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
map:
  - addon_config:rw
  - media:rw
  - share:rw
ports:
  6595/tcp: 6595
ports_description:
  6595/tcp: "Deemix WebUI"
ingress: true
ingress_port: 6595
panel_title: Deemix
panel_icon: "mdi:music-circle"

options:
  env_vars:
    - name: DEEMIX_MUSIC_DIR
      value: /media/deemix
  telegram_enabled: false
  telegram_token: ""
  whitelist_enabled: true
  whitelist_ids: ""
  deemix_bitrate_lock: false
  audd_api_key: ""
  openai_api_key: ""
  whisper_url: ""
schema:
  env_vars:
    - name: "match(^[A-Za-z_][A-Za-z0-9_]*$)"
      value: "str"
  telegram_enabled: bool
  telegram_token: "str?"
  whitelist_enabled: bool
  whitelist_ids: "str?"
  deemix_bitrate_lock: bool
  audd_api_key: "str?"
  openai_api_key: "str?"
  whisper_url: "str?"
