name: "Deemix with Telegram Bot"
slug: "deemix"
version: "4.7.0-2"
description: "High-quality music downloader with a Telegram bot: Remote, chat-based control for automated downloads."
url: "https://github.com/theodorx7/ha-deemix/"
image: "ghcr.io/theodorx7/ha-deemix"
backup_exclude:
  - "**/logs/**"
arch:
  - aarch64
  - amd64
init: false
startup: application
boot: auto
map:
  - addon_config:rw
  - media:rw
  - share:rw
ports:
  6595/tcp: 6595
ports_description:
  6595/tcp: "Deemix WebUI"
webui: "http://[HOST]:[PORT:6595]"

options:
  env_vars:
    - name: DEEMIX_MUSIC_DIR
      value: /media/MUSIC/! downloads/
  # НОВЫЕ ОПЦИИ для Teleemix:
  telegram_enabled: true
  telegram_token: ""
  deemix_arl: ""
  deemix_bitrate: 9
  deemix_bitrate_lock: false
  whitelist_enabled: true
  whitelist_ids: []
  audd_api_key: ""
  openai_api_key: ""
  whisper_url: ""
schema:
  env_vars:
    - name: "match(^[A-Za-z_][A-Za-z0-9_]*$)"
      value: "str"
  # НОВЫЕ СХЕМЫ для Teleemix:
  telegram_enabled: bool
  telegram_token: "str?"
  deemix_arl: "str?"
  deemix_bitrate: "list(1|3|9)"
  deemix_bitrate_lock: bool
  whitelist_enabled: bool
  whitelist_ids:
    - "int?"
  audd_api_key: "str?"
  openai_api_key: "str?"
  whisper_url: "str?"
